version: 2
jobs:
   build:
     working_directory: ~/pleasings
     docker:
       - image: thoughtmachine/pleasings:latest
     steps:
       - checkout
       - run:
           name: Build
           command: ./pleasew build -p -v 2 --exclude //android/example2/...
       - run:
           name: Test
           command: ./pleasew test -p -v 2 --exclude //android/example2/...
       - store_test_results:
           path: plz-out/log/test_results.xml
